#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.8

pipelines:
  default:
    - parallel:
      - step:
          name: Test
          caches:
            - pip
          script:
            - if [ -f test_requirements.txt ]; then pip install -r test_requirements.txt; fi
            - pytest -v tests/* --junitxml=test-reports/report.xml
      - step:
          name: Lint code
          script:
            - flake8 . --extend-exclude=dist,build --show-source --statistics
      - step:
          name: Static types checking
          script:
            - cd src
            - mypy .