name: Update_documentation

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements/tests.txt

      - name: Update documentation
        run: |
          pdoc -f --html -o docs src/signals_notebook

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'docs'
